{
 "title": "Redis Cluster Total",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "CLUSTER_ID", "label": "cluster_id", "query": "${VAR_CLUSTER_ID}" }
  ]
 },
 "panels": [
  {
   "title": "Cluster State",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, redis_cluster_state{alias=\"$CLUSTER_ID\"})"
    }
   ]
  },
  {
   "title": "Cluster Clients",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (redis_connected_clients{alias=\"$CLUSTER_ID\"})"
    }
   ]
  },
  {
   "title": "Master Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (redis_instance_info {alias=\"$CLUSTER_ID\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "slave nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (redis_instance_info {alias = \"$CLUSTER_ID\", role = \"slave\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (redis_memory_used_bytes{alias=\"$CLUSTER_ID\"}) / sum (redis_config_maxmemory{alias=\"$CLUSTER_ID\"}))"
    }
   ]
  },
  {
   "title": "Cluster Memory Max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (redis_instance_info {alias = \"$CLUSTER_ID\", role = \"master\"} * on (addr) group_left redis_config_maxmemory {alias = \"$CLUSTER_ID\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Used Peak",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (redis_instance_info{alias=\"$CLUSTER_ID\", role = \"master\"} * on(addr) group_left redis_memory_used_peak_bytes {alias = \"$CLUSTER_ID\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (redis_instance_info{alias=\"$CLUSTER_ID\", role = \"master\"} * on(addr) group_left redis_memory_used_bytes {alias = \"$CLUSTER_ID\"})"
    }
   ]
  },
  {
   "title": "Cluster Total Items",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_instance_info {alias=\"$CLUSTER_ID\", role=\"master\"} * on (addr) group_left sum (redis_db_keys{alias=~\"$CLUSTER_ID\"}) by (addr))",
     "legendFormat": "total items"
    }
   ]
  },
  {
   "title": "Cluster Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_keyspace_hits_total{alias=\"$CLUSTER_ID\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(irate(redis_keyspace_misses_total{alias=\"$CLUSTER_ID\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{alias=\"$CLUSTER_ID\"}",
     "legendFormat": "{{ addr }}"
    }
   ]
  },
  {
   "title": "Memory Usage Detail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(1, redis_config_maxmemory{alias=\"$CLUSTER_ID\"})",
     "legendFormat": "max"
    },
    {
     "expr": "redis_memory_used_bytes{alias=~\"$CLUSTER_ID\"} ",
     "legendFormat": "{{addr}} used"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{alias=\"$CLUSTER_ID\"}[5m])",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Network I/O Detail",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{alias=\"$CLUSTER_ID\"}[5m])"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{alias=\"$CLUSTER_ID\"}[5m])"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{alias=\"$CLUSTER_ID\"}[5m])",
     "legendFormat": "{{ addr }} input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{alias=\"$CLUSTER_ID\"}[5m])",
     "legendFormat": "{{ addr }} output"
    }
   ]
  },
  {
   "title": "Total Items",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{alias = \"$CLUSTER_ID\"}) by (addr)",
     "legendFormat": "{{ addr }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys Detail",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum (redis_db_keys{alias=\"$CLUSTER_ID\"}) by (addr) - sum (redis_db_keys_expiring{alias=\"$CLUSTER_ID\"}) by (addr)"
    },
    {
     "expr": "sum (redis_db_keys_expiring{alias=\"$CLUSTER_ID\"}) by (addr)"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_db_keys{alias=\"$CLUSTER_ID\"} - redis_db_keys_expiring{alias=\"$CLUSTER_ID\"}",
     "legendFormat": "{{ addr }} not expiring"
    },
    {
     "expr": "redis_db_keys_expiring{alias=\"$CLUSTER_ID\"}",
     "legendFormat": "{{ addr }} expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{alias=\"$CLUSTER_ID\"}[5m])) by (addr)",
     "legendFormat": "{{ addr }} expired"
    },
    {
     "expr": "sum (rate(redis_evicted_keys_total{alias=\"$CLUSTER_ID\"}[5m])) by (addr)",
     "legendFormat": "{{ addr }} evicted"
    }
   ]
  },
  {
   "title": "Slow Log",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_slowlog_last_id{alias=~\"$CLUSTER_ID\"}[5m])",
     "legendFormat": "{{ addr }}"
    }
   ]
  }
 ]
}