{
 "title": "Redis Cluster",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "CLUSTER_ID", "label": "cluster_id", "query": "${VAR_CLUSTER_ID}" },
   {
    "name": "addr",
    "query": "label_values(redis_up{alias=~\"$CLUSTER_ID\"}, addr)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Redis Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_up{addr=\"${addr}\"}"
    }
   ]
  },
  {
   "title": "Replication Role",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "redis_instance_info{addr=\"${addr}\", role!=\"\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{addr=~\"$addr\"}  / redis_config_maxmemory{addr=~\"$addr\"} )"
    }
   ]
  },
  {
   "title": "Memory Fragmentation",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_memory_used_rss_bytes{addr=~\"$addr\"} / redis_memory_used_bytes{addr=~\"$addr\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Master / Slaves",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "label_join(redis_slave_info{addr=\"${addr}\"}, \"master_addr\", \":\", \"master_host\", \"master_port\")"
    },
    {
     "expr": "label_join(redis_connected_slave_offset{addr=\"${addr}\"}, \"slave_addr\", \":\", \"slave_ip\", \"slave_port\")"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_instantaneous_ops_per_sec{addr=~\"$addr\"}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=\"$addr\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=\"$addr\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$addr\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_config_maxmemory{addr=~\"$addr\"} ",
     "legendFormat": "max"
    },
    {
     "expr": "redis_memory_used_peak_bytes{addr=~\"$addr\"} ",
     "legendFormat": "peak"
    },
    {
     "expr": "redis_memory_used_rss_bytes{addr=~\"$addr\"} ",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "redis_instantaneous_input_kbps{addr=\"$addr\"}",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "redis_instantaneous_output_kbps{addr=\"$addr\"}",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(redis_used_cpu_sys{addr=~'$addr'}[5m])",
     "legendFormat": "sys"
    },
    {
     "expr": "irate(redis_used_cpu_user{addr=~'$addr'}[5m])",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) - sum (redis_db_keys_expiring{addr=~\"$addr\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$addr\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{addr=~\"$addr\"}[5m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Slow Log",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_slowlog_last_id{addr=~\"$addr\"}[5m])",
     "legendFormat": "slow log"
    }
   ]
  }
 ]
}