{
 "title": "Redis Statistic",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "TOP", "label": "top", "query": "10,20,30" }
  ]
 },
 "panels": [
  {
   "title": "QPS Top $TOP",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort(topk($TOP, rate(redis_commands_processed_total[5m])))"
    }
   ]
  },
  {
   "title": "Clients Top $TOP",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sort(topK($TOP, redis_connected_clients))"
    }
   ]
  },
  {
   "title": "Memory Used Top $TOP",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sort(topk($TOP, 100 * (redis_memory_used_bytes  / redis_config_maxmemory )))"
    }
   ]
  },
  {
   "title": "Network Input Top $TOP",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort(topk($TOP, redis_instantaneous_input_kbps))"
    }
   ]
  },
  {
   "title": "Network Output Top $TOP",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sort(topk($TOP, redis_instantaneous_output_kbps))"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "topk($TOP, redis_instantaneous_input_kbps > 1024)",
     "legendFormat": "{{ addr }} input "
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "topk($TOP, redis_instantaneous_output_kbps > 1024)",
     "legendFormat": "{{ addr }} output"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk($TOP, rate(redis_used_cpu_sys[5m]) > 0.2)",
     "legendFormat": "used cpu sys {{ addr }}"
    },
    {
     "expr": "topk($TOP, rate(redis_used_cpu_user[5m]) > 0.2)",
     "legendFormat": "used cpu user{{ addr }}"
    }
   ]
  },
  {
   "title": "QPS Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total[5m]))",
     "legendFormat": "总QPS"
    }
   ]
  },
  {
   "title": "Clients Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(redis_connected_clients)", "legendFormat": "clients" }
   ]
  }
 ]
}